
#--------------------配置 service discovery------------
spring:
  application:
    name: eureka-client-core
  zipkin:
    base-url: http://localhost:8001
  sleuth:
      sampler:
        percentage: 1.0
server:
  port: 8030

eureka:
  instance:
    hostname: localhost
  client:
     serviceUrl:
      defaultZone: http://localhost:8000/eureka/