
#--------------------配置 service discovery------------
spring:
  application:
    name: eureka-client-provide
server:
  port: 8010

eureka:
  instance:
    hostname: localhost
  client:
     serviceUrl:
      defaultZone: http://localhost:8000/eureka/