
#--------------------配置 service discovery------------
spring:
  application:
    name: api-gateway
server:
  port: 8021

eureka:
  instance:
    hostname: localhost
  client:
     serviceUrl:
      defaultZone: http://localhost:8000/eureka/
zuul:
  routes:
    api-a:
      path: /api/**
      serviceId: eureka_client_consumer_fegin_hystrix
    api-b:
      path: /api-a/**
      serviceId: eureka_client_consumer_fegin_hystrix_a