
#--------------------配置 service discovery------------
spring:
  application:
    name: config-server-git
  cloud:
      config:
        server:
          git:
            uri: https://github.com/zhouzgang/config-repo-demo.git
server:
  port: 8014
